[package]
edition = "2021"
license = "MIT OR Apache-2.0 OR CC0-1.0"
name = "ace"
publish = false
rust-version = "1.72"
version = "0.1.0"

[dependencies]
anyhow = "1"
async-openai = "0.21"
byteorder = "1"
bytes = "1"
cpal = "0.15"
crossbeam = "0.8"
deepgram = {path = "deepgram-rust-sdk"}
eframe = {version = "0.27", default-features = false, features = ["default_fonts", "glow", "persistence"]}
egui = "0.27"
egui-tetra2 = {git = "https://github.com/trevyn/egui-tetra2", branch = "main"}
egui_extras = {version = "0.27", features = ["image"]}
egui_node_graph2 = "0.5"
ehttp = "0.5"
env_logger = "0.11"
freeverb = "0.1"
futures = "0.3"
hound = "3"
image = {version = "0.25", default-features = false, features = ["jpeg", "png"]}
log = "0.4"
once_cell = "1"
poll-promise = {version = "0.3", default-features = false}
regex = "1"
reqwest = "0.12"
rfd = "0.14"
serde = {version = "1.0.196", features = ["derive"]}
serde_json = "1"
stream-cancel = "0.8"
syntect = {version = "5", default-features = false, features = ["default-fancy"]}
tetra = {version = "0.8", default-features = false, features = ["sdl2_bundled", "sdl2_static_link"]}
tokio = {version = "1", features = ["full"]}
tracked = "0.5"
turbosql = "0.10"

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true

[patch.crates-io]
tetra = {git = "https://github.com/17cupsofcoffee/tetra", branch = "main"}

# If you want to use the bleeding edge version of egui and eframe:
# egui = { git = "https://github.com/emilk/egui", branch = "master" }
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# egui = { path = "../egui/crates/egui" }
# eframe = { path = "../egui/crates/eframe" }
